name: Deploy Docker Image

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t tonijro31/node-apirest:latest .
          docker push tonijro31/node-apirest:latest

      
      - name: Deploy Docker container
        run: |
          docker pull tonijro31/node-apirest:latest
          docker run -d -p 3000:4200 tonijro31/node-apirest:latest


